export default {
  signup: {
    UserData: {
      email: 'test@QuickCredit.com',
      firstname: 'karenzi',
      lastname: 'david',
      password: 'Quick1234@56',
      address: 'gisozi',
    },
    UserToken: {
      email: 'test@QuickCredit.com',
      firstname: 'karenzi',
      lastname: 'david',
      password: 'Quick1234@56',
      address: 'gisozi',
      status: 'Unverified',
      isAdmin: false,
    },
    AdminInfo: {
      firstname: 'runoro',
      lastname: 'isaiah',
      email: 'admin@test.com',
      password: 'admin1234',
      address: 'Quick-Credit HeadQuaters',
    },
    validAdmin: {
      firstname: 'runoro',
      lastname: 'isaiah',
      email: 'admin1@test.com',
      password: '$2a$10$b4Sf8hjFM5vWaCx56POPmuILIiAgZNlkJR241hKOlBo8lb2atA4KS',
      address: 'Quick-Credit HeadQuaters',
      isAdmin: true,
    },
    AdminToken: {
      firstname: 'runoro',
      lastname: 'isaiah',
      email: 'admin@test.com',
      password: 'admin1234',
      address: 'Quick-Credit HeadQuaters',
      isAdmin: true,
    },
    NewUserData: {
      email: 'test1@QuickCredit.com',
      firstname: 'karenzi',
      lastname: 'david',
      password: 'Quick1234@56',
      address: 'gisozi',
    },
    NewUserToken: {
      email: 'test@QuickCredit.com',
      firstname: 'karenzi',
      lastname: 'david',
      password: 'Quick1234@56',
      address: 'gisozi',
      status: 'Unverified',
      isAdmin: false,
    },
    NewUserData2: {
      email: 'test2@QuickCredit.com',
      firstname: 'karenzi',
      lastname: 'david',
      password: 'Quick1234@56',
      address: 'gisozi',
    },
    NewUserData2Token: {
      email: 'test2@QuickCredit.com',
      ffirstname: 'karenzi',
      lastname: 'david',
      password: 'Quick1234@56',
      address: 'gisozi',
      status: 'Unverified',
      isAdmin: false,
    },
    missingUserInfo: {
      firstname: 'ka',
      lastname: 'david',
      email: 'test@QuickCredit.com',
      password: 'Quick1234@56',
      status: 'Unverified',
      isAdmin: false,
    },
  },
  login: {
    UserLogin: {
      email: 'test@QuickCredit.com',
      password: 'Quick1234@56',
    },
  },
};
